### ISSUE TITLE
AESD Endgame

### ISSUE THREAD

**Issue by raffaelepojer** [raffaelepojer/AESD#12]
**Need to be done:** 

- [x] check if it works with over 50% of the images
- [x] tune the parameters for the mask
- [x] check if with homography the detection is fine
- [ ] write documentation
- [x] fix errors that come out with some images 

Other tasks can be added to the list if necessary

**Comment by raffaelepojer** [comment]
**We need to investigate why we get errors with certain images**

Reported errors examples:

> image5.jpg

```
Traceback (most recent call last):
  File "/Users/raffaele/Dev/AESD-prj/AESD/main.py", line 49, in <module>
    found = det.detectSing(s)
  File "/Users/raffaele/Dev/AESD-prj/AESD/detect.py", line 326, in detectSing
    matches = flann.knnMatch(des1,des2,k=2)
cv2.error: OpenCV(4.5.1) /tmp/opencv-20210108-71707-10ezvrg/opencv-4.5.1/modules/flann/src/miniflann.cpp:336: error: (-210:Unsupported format or combination of formats) in function 'buildIndex_'
> type=0
> 

```

> image24.jpg

```
Traceback (most recent call last):
  File "/Users/raffaele/Dev/AESD-prj/AESD/main.py", line 49, in <module>
    found = det.detectSing(s)
  File "/Users/raffaele/Dev/AESD-prj/AESD/detect.py", line 326, in detectSing
    matches = flann.knnMatch(des1,des2,k=2)
cv2.error: OpenCV(4.5.1) /tmp/opencv-20210108-71707-10ezvrg/opencv-4.5.1/modules/flann/src/miniflann.cpp:336: error: (-210:Unsupported format or combination of formats) in function 'buildIndex_'
> type=0
> 
```
These are two different types of error that we get.

- Python version 3.9.1
- OpenCv version 4.5.1
